name: "Crowdsec"
description: "CrowdSec - the open-source and participative IPS"
url: "https://github.com/crowdsecurity/home-assistant-addons/tree/main/crowdsec"
version: "1.3.0"
slug: "crowdsec"
init: false
arch:
  - amd64
  - armhf
  - aarch64
  - armv7
  - i386
#image: "ghcr.io/crowdsecurity/{arch}-addon-crowdsec"
options:
  acquisition: |
    ---
    source: journalctl
    journalctl_filter: 
      - "--directory=/var/log/journal/"
    labels:
      type: syslog
  collections:
    - crowdsecurity/home-assistant
  parsers: []
  scenarios: []
  postoverflows: []
  parsers_to_disable:
    - crowdsecurity/whitelists
  scenarios_to_disable: []
  console_enroll_key: ""
  console_enroll_name: ""
  console_enroll_tags: []
  disable_online_api: false
environment:
  CONFIG_FILE: "/config/.storage/crowdsec/config/config.yaml"
schema:
  acquisition: str
  collections:
    - str
  parsers:
    - str
  scenarios:
    - str
  postoverflows:
    - str
  parsers_to_disable:
    - str
  scenarios_to_disable:
    - str
  console_enroll_key: str
  console_enroll_name: str
  console_enroll_tags:
    - str
  disable_online_api: bool
map:
  - config:rw
advanced: true
panel_icon: mdi:console
panel_title: Crowdsec
journald: true